### ISSUE TITLE
все линты, и некоторые другие пакеты должны быть в devDependencies

### ISSUE THREAD

**Issue by SergProduction** [momomog/TechNews#4]
https://github.com/momomog/TechNews/blob/3cb61dc4db1eaef41aa4a16315ddb8fc1b0661a9/client/tech-news-app/package.json#L44

**Comment by momomog** [comment]
Есть такое. После eject'a здесь не трогал ничего, есть где прибраться 👍

**Comment by momomog** [comment]
Подправил
